### ISSUE TITLE
Tab PreventDefault

### ISSUE THREAD

**Issue by cdcharlebois** [mendixlabs/rich-text#14]
Would be nice to preventDefault on the tab key, so I can add tabs to my content without switching to a new input on the page

**Comment by cdcharlebois** [comment]
Mx v7.13.1, btw

**Comment by Andries-Smit** [comment]
Hi Conner,

Thanks for reporting this issue. Our implementation working as you expect.
https://texteditorwidget.mxapps.io/

Though Mendix replaced the focus manager in version 7.11, which probably caused this issue. We will look into this

Cheers, 
Andries

**Comment by Andries-Smit** [comment]
Issue is resolved in version 1.2.0
