### ISSUE TITLE
Tabbing

### ISSUE THREAD

**Issue by mlehane1** [mendixlabs/rich-text#18]
It's great that you "fixed" the tabbing issue, but I'd like to have the tabbing still work to move into the next field. Can we make it configurable at design time?

**Comment by Andries-Smit** [comment]
Hi Marc,

We will discuss it with the  product owner.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Hi Marc,

We will plan this feature for next sprint.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Hi Marc,

Tab action function is add in version 1.3.0
Available trough the Mendix appstore https://appstore.home.mendix.com/link/app/74889/

Cheers,
Andries
