### ISSUE TITLE
First letter is not converted by IME

### ISSUE THREAD

**Issue by bs-baba** [mendixlabs/rich-text#19]
Hi,

When entering a double-byte character on a blank line, the first character is confirmed before the IME converts it.
For example, in the case of Japanese, if you type "wa" it is correct to convert it to the letter 'わ'.
However, with this widget, the first 'w' is confirmed before the convertion and only the second 'a' is subject to IME conversion. And letter 'a' corresponds to the Japanese letter 'あ'.
As a result, it will be "wあ". This is incorrect.

- Occur when using Google Chrome. It does not occur in Edge.
- It does not depend on the type of IME. It occurs in both Windows standard IME and Google IME.

![image](https://user-images.githubusercontent.com/38234320/42253345-53c4af20-7f7c-11e8-942e-dd0b2842f7cf.png)

Thank you,
Naomichi

**Comment by Andries-Smit** [comment]
Dear Naomichi,

Thanks for reporting this issue, we will look into this.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Dear Naomichi,

Does this issue only occur in this custom widget or does it also occur with the standard text inputs on chrome?

Thanks, Andries

**Comment by bs-baba** [comment]
Hi Andries,

Thanks for reply.

This issue occurs only in this custom widget.
Standard text inputs works fine.

Regards,
 Naomichi

**Comment by Andries-Smit** [comment]
Dear Naomichi,

We released a version 1.3.1 in the appstore https://appstore.home.mendix.com/link/app/74889/ which includes an IME fix. Could you please let us know if this solves your issue?

Thank you, Andries

**Comment by bs-baba** [comment]
Great!
Thanks for your help!
