### ISSUE TITLE
Simple Rich Text Editor is not working in Mx 7.16.0

### ISSUE THREAD

**Issue by keilt** [mendixlabs/rich-text#21]
Using the simple rich text editor in Mx 7.16.0 is showing the following error:

Version '0.1' of the 'Simple Rich Text Editor' widget is not compatible with Mendix 7.

I downloaded version 1.30 from the Appstore as well I tried version 1.30 from GitHub

**Comment by Andries-Smit** [comment]
Dear Tobias,

Thanks for reporting this issue. I have some trouble reproducing it.
I created a clean new 7.16 project and imported 1.3.0 from the app store
https://appstore.home.mendix.com/link/app/74889/

No trouble with the editor.

Could you please provide us with a sample project with this issue?

PS: Disdyou try remove the file from the <projectdir>/widgets 
or pres F5 to reload?

With kind regards,
Andries

**Comment by keilt** [comment]
Hi Andries,

I did a new checkout and tried it again with having success. I'm not able to reproduce the initial issue again.
Can be closed.

Cheers,
Tobias
