### ISSUE TITLE
object not updated nor on change triggered when pasting text

### ISSUE THREAD

**Issue by joppevg** [mendixlabs/rich-text#3]
If text is pasted (ctrl-v) into the textarea the underlying object is not updated until a character is added nor is the OnChange triggered.

**Comment by edwinmp** [comment]
Hi @joppevg, thanks for raising this. Will look into it ASAP.

**Comment by edwinmp** [comment]
Hi @joppevg, this issue has been fixed in version [1.0.2](https://github.com/mendixlabs/rich-text/releases/tag/1.0.2). Please have a look and let me know if it's satisfactory.
