### ISSUE TITLE
Inconsistent with default Mx input widgets

### ISSUE THREAD

**Issue by JelleDekker** [mendixlabs/rich-text#6]
This widget is inconsistent with standard Mendix input widgets. It offers no way of adding a label, nor does it handle validation feedback.

**Comment by Andries-Smit** [comment]
Hi Jelle, 

Indeed, labels are not supported at the moment, in the future we might add it. 
At the moment there is no way to provide labels in the same way as the core widgets, with the same exact behavior. 
For now, you could create a text and use it as labels.

The missing validation is deed an issue.  We will add it to our sprint backlog. 

Thanks for your feedback,
Andries

**Comment by Andries-Smit** [comment]
The inline validation is added in the new release https://appstore.home.mendix.com/link/app/74889/ version 1.1.0

Labels will not be added to the custom widgets, for now.
