### ISSUE TITLE
Open links in a new browser tab

### ISSUE THREAD

**Issue by royhermans** [mendixlabs/rich-text#7]
![screenshot_17](https://user-images.githubusercontent.com/32068390/33480645-b9db2378-d691-11e7-96b3-cdc84191e5a7.png)
Currently when you add a link and click it the website is opened in the current browser tab. Is it possible to add an option so you can set it to open in a new browser tab?
With the current situation users leave the app when clicking on a link that refers to an external website.

Mendix version 7.5.1

**Comment by edwinmp** [comment]
Hi @royhermans, I could replicate your issue. By default, any links created in the editor posses the  `target="_blank"` that lets them open in a new tab.

![richtext](https://user-images.githubusercontent.com/5672438/33765749-5e1fa01e-dc2b-11e7-8aa4-0eb6cd35c864.gif)

If it persists for you, could you please provide a fresh demo project and steps to replicate it.

**Comment by royhermans** [comment]
Hi, my bad, it's the sanitize java action again :( so no further action is needed, thank you for your time!
