### ISSUE TITLE
Tabs only work when editing

### ISSUE THREAD

**Issue by royhermans** [mendixlabs/rich-text#8]
We encountered the following issue:
You can add tabs when editing the text but when you save your content and view it the tabs are removed:

![screenshot_18](https://user-images.githubusercontent.com/32068390/33481951-0c128604-d697-11e7-998f-dc974d22f715.png)

![screenshot_19](https://user-images.githubusercontent.com/32068390/33481953-0c2b9ef0-d697-11e7-85bd-e02f68136d5a.png)

I used bullets in this example but the same issue applies when using tabs on just text for example without bullets.

Mendix version 7.5.1

**Comment by edwinmp** [comment]
Hi @royhermans thanks for raising this... will look into it asap.

**Comment by royhermans** [comment]
Hi @edwinmp ,

Do you have an estimate for a possible solution?
Thanks in advance!

**Comment by edwinmp** [comment]
Hi @royhermans, we have a release scheduled for the coming week. In the meantime, you can checkout the beta [here](https://github.com/FlockOfBirds/rich-text/releases/tag/v1.1.0-beta).

Thanks.

**Comment by Andries-Smit** [comment]
This issue is addressed in the new release https://appstore.home.mendix.com/link/app/74889/ version 1.1.0
Please let us know if this solves your problem
