### ISSUE TITLE
Loosing html-format tags in template grid

### ISSUE THREAD

**Issue by RJZomer** [mendixlabs/rich-text#9]
I'm using Mendix 7.10

- Input with widget is in a dataview
- For overview purposes we use a straight forward template grid with the widget just displaying X number of objects. It seems that the template grid if the rich-text widget is included is corrupting the (html)text, and actually loosing breaks "br>" and e.g. bullets "ul>li>"
- So after running template grid overview, and going back to the dataview the html-format-tags it becomes clear that quite some html-tags are lost!

see attachments. 

**step 1 dataview (both with widget and a textbox to see the actual html)**
![1 start dataview](https://user-images.githubusercontent.com/35564116/35096812-e253b4b4-fc4d-11e7-9014-490236f90bb8.jpg)

**step2 dataview after running template grid overview, some lost html-tags
![2 result after template grid back in dataview](https://user-images.githubusercontent.com/35564116/35097016-9d73548e-fc4e-11e7-90a1-76b58faf5a98.jpg)

for overview enclosed an impression of the template grid
![template grid](https://user-images.githubusercontent.com/35564116/35096994-88854aaa-fc4e-11e7-9d4d-e893d3a66812.jpg)

**Comment by Andries-Smit** [comment]
Dear Zomer.

Thank you for reporting this issue. We are currently working on an update for the Rich Text widget. We will include this case too.

Cheers, Andries

**Comment by Andries-Smit** [comment]
This issue is addressed in the new release https://appstore.home.mendix.com/link/app/74889/ version 1.1.0
Please let us know if this solves your problem
